# File: azure-pipelines.yml
# Build Name / Format
name: PowerAppsTestAutomation-$(date:yyyyMMdd)$(rev:.r)

trigger: none
pool:
  vmImage: windows-latest
  demands:
  - msbuild
  - visualstudio
  - vstest
variables:
- name: PortalUrl
  value: https://make.powerapps.com
  # Browser PrivateMode usage (true/false)
- name: PrivateMode
  value: true
  # FileName where TestAutomationURLs are stored in JSON format
- name: TestUrlFileName 
  value: TestURLs.json
  # Project name of repo containing TestAutomationURLs (spaces should be encoded as %20)
  # Example: Contoso Test Framework --> Contoso%20Test%20Framework
- name: LocalProjectName
  value: PowerAppsTestAutomation
- name: browserType
  value: Chrome
- name: loginMethod
  value: FederatedIdentity

steps:
- checkout: self
- checkout: PowerAppsTestAutomation
#- template: localsteps.yml # Provide optional local YAML template here
- template: frameworksteps.yml@PowerAppsTestAutomation
  parameters:
    OnlineUsername: $(OnlineUsername)
    OnlinePassword: $(OnlinePassword)
    OnlineUrl: $(PortalUrl)
    BrowserType: $(browserType)
    # File location format is /s/TeamProjectName/FilePathToTestAutomationURLs.json
    TestAutomationURLFilePath: $(Build.SourcesDirectory)\$(LocalProjectName)\$(TestUrlFileName)
    UsePrivateMode: $(PrivateMode)
    LoginMethod: $(loginMethod)

resources:
repositories:
  - repository: PowerAppsTestAutomation
    type: github
    # GitHub Repo(e.g. <FORK>/PowerAppsTestAutomation)
    # Recommended to Fork or Duplicate if custom auth flows are required
    name: live1206/PowerAppsTestAutomation
    ref: master
    # Name of the GitHub OAuth ADO Service Connection
    endpoint: GitHub-PowerApps-Testing